spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image_download?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    database-platform:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
amazon:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: 'eu-central-1'