spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: etpa
    password: etpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
